spring:
  application:
    name: card-lifecycle-svc
  datasource:
    url: ${CARD_LIFECYCLE_DB_URL}
    username: ${CARD_LIFECYCLE_DB_USER}
    password: ${CARD_LIFECYCLE_DB_PASSWORD}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    properties:
      schema.registry.url: ${SCHEMA_REGISTRY_URL}
      security.protocol: ${KAFKA_SECURITY_PROTOCOL:SASL_SSL}
      sasl.mechanism: SCRAM-SHA-512
      sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME:}" password="${KAFKA_PASSWORD:}";
    producer:
      client-id: card-lifecycle-svc
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        auto.register.schemas: false
        use.latest.version: true
    consumer:
      auto-offset-reset: latest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        specific.avro.reader: true
    listener:
      ack-mode: record

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
